---
name: Build - Windows - Solution

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "source/**"
      - "vcproj/**"
      - "vcpkg.json"
  merge_group:
  push:
    paths:
      - "source/**"
      - "vcproj/**"
      - "vcpkg.json"
    branches:
      - main

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: "-j 2"
  GITHUB_WORKSPACE: ${{ github.workspace }}
  VCPKG_INSTALLED_DIR: ${{ github.workspace }}/vcpkg_installed
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_DEFAULT_TRIPLET: x64-windows
  VCPKG_TRIPLET: x64-windows

jobs:
  cancel-runs:
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  job:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    permissions:
      actions: write
      contents: read
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        buildtype: [Release, Debug]
        include:
          - os: windows-2022
            triplet: x64-windows
    steps:
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Resolve vcpkg baseline
        id: vcpkg-step
        run: |
          $json = Get-Content vcpkg.json -Raw | ConvertFrom-Json
          $vcpkgCommitId = $json.'builtin-baseline'
          Write-Host "vcpkg commit ID: $vcpkgCommitId"
          echo "VCPKG_GIT_COMMIT_ID=$vcpkgCommitId" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/vcpkg_installed
            ${{ github.workspace }}/vcpkg/downloads
            ${{ github.workspace }}/vcpkg/packages
          key: vcpkg-${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}-${{ env.VCPKG_GIT_COMMIT_ID }}
          restore-keys: |
            vcpkg-${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}-
            vcpkg-${{ matrix.triplet }}-

      - name: Setup vcpkg and install dependencies
        uses: lukka/run-vcpkg@v11
        env:
          VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
        with:
          vcpkgGitURL: "https://github.com/microsoft/vcpkg.git"
          vcpkgGitCommitId: ${{ env.VCPKG_GIT_COMMIT_ID }}
          vcpkgJsonGlob: vcpkg.json
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          doNotCache: false
          runVcpkgInstall: true

      - name: Print useful paths
        run: |
          Write-Host "Workspace: $env:GITHUB_WORKSPACE"
          Write-Host "Vcpkg Path: $env:VCPKG_ROOT"
          Write-Host "Installed Path: $env:VCPKG_INSTALLED_DIR"
          Write-Host "Triplet: ${{ matrix.triplet }}"

      - name: Build project
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
          VCPKG_BINARY_SOURCES: clear
        run: msbuild.exe /p:VcpkgEnableManifest=true /p:VCPKG_ROOT="$env:VCPKG_ROOT" /p:VcpkgInstalledDir="$env:VCPKG_INSTALLED_DIR" /p:Configuration=${{ matrix.buildtype }} /p:Platform=x64 /p:GITHUB_WORKSPACE="$env:GITHUB_WORKSPACE" vcproj/RME.sln

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.os }}-${{ matrix.buildtype }}
          path: |
            ${{ github.workspace }}/vcproj/Project/x64/${{ matrix.buildtype }}/
